### ISSUE TITLE
Repeat and loop function

### ISSUE THREAD

**Issue by DavidNyan10** [vveeps/stolfo#3]
### Repeat
```
Repeats the current track a given number of times.
   For example:
       - repeat 3
       - repeat 5
       - repeat 10
```
Default is 1 and 0 makes it repeat forever. 

I'm thinking of something like having a for loop and calling play_next inside it after the song playing is done but when I tried it's a lot more complicated (mayb im just dumb)

### Loop
```
Toggles the player's looping.
   When enabled, the queue is looped and it's restored when disabled.
```

Same as above, but instead of play_next, it moves the current track to the bottom of the queue (queue[length-1]). Maybe keep track of how many times it's been moving the top finished songs to the bottom, find the modulus of that with the queue length, and remove the number of songs from that answer. e.g. if the song length is 13 and it has moved for 30 times, then when loop is disabled it will remove 30mod13 = 4 songs from the bottom. Again, it's easier said than done. 

I just don't understand the OO classes and the arguments to work with it.

**Comment by vveeps** [comment]
i have a bunch of ideas on what to implement, track/queue looping being one of them

i havent had the time or motivation to work on the bot lately but i'll try to get stuff done soon, hopefully
